/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lby5o5J6p10
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { getCollectionProducts } from 'lib/shopify';
import type { Product } from 'lib/shopify/types';
import Link from 'next/link';

export async function HomeComponent() {
  const lighters = await getCollectionProducts({ collection: 'lighters' });
  const lighter = lighters?.[0];

  // gets the first image
  const getImage = (product: Product | false) => {
    if (product) return product.images[0];
    return {
      url: '',
      altText: '',
      width: 0,
      height: 0
    };
  };
  // Not sure why revalidate not working
  // console.log(homepageItems);
  let lighterImage = getImage(lighter || false) as unknown as {
    url: string;
    altText: string;
    width: number;
    height: number;
  };
  return (
    <div className="flex min-h-[100dvh] flex-col">
      <div className="flex-1">
        <section className="w-full bg-[#1b1b1b] py-12 text-white md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Unleash Your Inner Ninja Shanti
                  </h1>
                  <p className="max-w-[550px] text-muted-foreground md:text-xl">
                    At Ninja Shanti, we blend the stealth and resilience of a ninja with the
                    tranquility and harmony of shanti, creating a unique clothing brand that speaks
                    to the modern warrior's spirit.
                  </p>
                  <p className="max-w-[550px] text-muted-foreground md:text-xl">
                    Our products, from hats and lighters to our line of t-shirts, embody this
                    powerful fusion, offering style and functionality for those who navigate life's
                    challenges with grace and strength.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="/search?q="
                    className="inline-flex h-10 items-center justify-center rounded-md bg-[#00b894] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#00b894]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Shop Now
                  </Link>
                  {/* <Link
                    href="/about"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-[#555] bg-[#1b1b1b] px-8 text-sm font-medium shadow-sm transition-colors hover:bg-[#555] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Learn More
                  </Link> */}
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width="550"
                height="550"
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section className="w-full bg-[#f5f5f5] py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-[#1b1b1b] px-3 py-1 text-sm text-white">
                  Featured Products
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Discover Our Unique Clothing Line
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Ninja Shanti offers a carefully curated selection of hats, lighters, and t-shirts
                  that blend modern style with traditional ninja and shanti elements. Explore our
                  collection and find the perfect piece to express your unique personality.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-[#00b894] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#00b894]/50 data-[state=open]:bg-[#00b894]/50">
                <img
                  src="/placeholder.svg"
                  width="200"
                  height="200"
                  alt="Product"
                  className="mx-auto aspect-square overflow-hidden rounded-lg object-cover object-center sm:w-full"
                />
                <div className="text-sm font-medium leading-none group-hover:underline">
                  Ninja Shanti Hat
                </div>
                <div className="line-clamp-2 text-sm leading-snug text-muted-foreground">
                  Blend stealth and tranquility with our signature ninja-inspired hat.
                </div>
              </div>
              <div className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-[#00b894] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#00b894]/50 data-[state=open]:bg-[#00b894]/50">
                <Link className="" href={`/product/${lighter?.handle}`}>
                  <img
                    src={lighterImage?.url}
                    width="200"
                    height="200"
                    alt={lighterImage?.altText}
                    className="mx-auto aspect-square overflow-hidden rounded-lg object-cover object-center sm:w-full"
                  />
                  <div className="text-sm font-medium leading-none group-hover:underline">
                    Ninja Shanti Lighter
                  </div>
                  <div className="line-clamp-2 text-sm leading-snug text-muted-foreground">
                    Ignite your inner flame with our sleek and durable ninja-inspired lighter.
                  </div>
                </Link>
              </div>
              <div className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-[#00b894] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#00b894]/50 data-[state=open]:bg-[#00b894]/50">
                <img
                  src="/placeholder.svg"
                  width="200"
                  height="200"
                  alt="Product"
                  className="mx-auto aspect-square overflow-hidden rounded-lg object-cover object-center sm:w-full"
                />
                <div className="text-sm font-medium leading-none group-hover:underline">
                  Ninja Shanti T-Shirt
                </div>
                <div className="line-clamp-2 text-sm leading-snug text-muted-foreground">
                  Embrace the balance of ninja stealth and shanti tranquility with our signature
                  t-shirt.
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function TurtleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 10 2 4v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3a8 8 0 1 0-16 0v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3l2-4h4Z" />
      <path d="M4.82 7.9 8 10" />
      <path d="M15.18 7.9 12 10" />
      <path d="M16.93 10H20a2 2 0 0 1 0 4H2" />
    </svg>
  );
}
